### ISSUE TITLE
训练新模型时遇到问题

### ISSUE THREAD

**Issue by RLSNLP** [zhiyiYo/Alpha-Gobang-Zero#1]
你好，我使用了你默认的参数进行训练，但是进行了一局自我博弈以后，就提示训练结束，已将当前模型保存到XXX。
请问这是什么原因呢？我检查的是运行到train.py的self.dataset.append(self.__self_play()) 这一行就不再继续运行了。

**Comment by zhiyiYo** [comment]
在 train.py 的第23行，在 `except` 后面加上 `KeyboardInterrupt` 看下问题出在哪

**Comment by RLSNLP** [comment]
> 在 train.py 的第23行，在 `except` 后面加上 `KeyboardInterrupt` 看下问题出在哪

可能是Python版本不对？我的是Python3.8版本，重写了save_model函数并且把wrapper去掉以后就可以正常跑了。

**Comment by zhiyiYo** [comment]
> > 在 train.py 的第23行，在 `except` 后面加上 `KeyboardInterrupt` 看下问题出在哪
> 
> 可能是Python版本不对？我的是Python3.8版本，重写了save_model函数并且把wrapper去掉以后就可以正常跑了。

在运行代码之前还是先看下 readme，按照里面的提示建好虚拟环境就不会出现这个问题，同时不建议把 save_model 装饰器去掉
