### ISSUE TITLE
請問怎樣在訓練的過程中自動儲存train_losses和games的檔案?

### ISSUE THREAD

**Issue by pingping2050** [zhiyiYo/Alpha-Gobang-Zero#2]
你好
請問如何在訓練中的每一次完成博弈後，都會自動儲存train_losses和games的json檔案到log文件夾裏?
我也想好像作者一樣紀錄train loss和game(對弈的棋譜)，但我發現只有(check_frequency=0)的時候,才會觸發BaseException as e才會進入save_model。

**Comment by zhiyiYo** [comment]
check_frequency 的整数倍就会保存模型呀(准确来说是保存比上次更强的模型），你可以把 check_frequency 调小试试

**Comment by zhiyiYo** [comment]
你可以在 `train.py` 的  `if (i+1) % self.check_frequency == 0` 前面加上保存棋谱还有损失的代码，具体保存的代码可以参考 `save_model` 函数。也许我应该考虑封装一个 `save_model` 函数，然后把异常处理装饰器重命名为 `exception_handler`。

**Comment by zhiyiYo** [comment]
我更新了代码，你现在可以在 `train.py` 的 221行 `if (i+1) % self.check_frequency == 0` 前面加上保存模型、损失和棋谱的代码，具体保存的代码可以是 `                self.save_model(f'policy_value_net_{i+1}', f'train_losses_{i+1}', f'games_{i+1}')
`

**Comment by pingping2050** [comment]
太好了，感謝作者更新和修改。
現在我可以進入測試模型時 先儲存當前模型,train loss和棋譜。

**Comment by zhiyiYo** [comment]
最好不要断点训练，因为我没把断点时候的 `i` 保存下来，会导致学习率没有恢复为退火后的值，损失曲线后期的波动可能就是因为我之前经常断点训练，有条件的话可以在服务器上连续跑上几天😊
