### ISSUE TITLE
AlphaZeroMCTS get_action node backup 有点难理解

### ISSUE THREAD

**Issue by haormj** [zhiyiYo/Alpha-Gobang-Zero#3]
zhiyiYo，你好：

首先非常感谢开源这个项目，正好最近个人对于这个比较感兴趣就看了相关代码，也进行了一些小调整，目标就是通过这个ai战胜我对象，如下代码

https://github.com/zhiyiYo/Alpha-Gobang-Zero/blob/master/alphazero/alpha_zero_mcts.py#L72

应该就是为了判断，游戏的获胜方是否是获取action方，board.current_player 这个会随着do_action变化，感觉修改为

```
value = 1 if winner == chess_board.current_player else -1
node.backup(value)
``` 
当然个人也没有完全看懂，不确认这样修改是否是可以的

**Comment by zhiyiYo** [comment]
你是说把反向传播放在 `elif winner is not None` 分支里面吗？就算游戏没有结束也要反向传播，增加祖先节点的 N 才对呀

**Comment by zhiyiYo** [comment]
@haormj

**Comment by haormj** [comment]
@zhiyiYo 等下，我fork下，修改之后给你看diff

**Comment by haormj** [comment]
@zhiyiYo 

https://github.com/haormj/Alpha-Gobang-Zero/commit/699e3eb752e1da3a9e425207cdc3c53953bb4922

按照这样修改之后，是否和你原来想表述的意思是一样的

**Comment by zhiyiYo** [comment]
感觉有点问题，加上负号的原因应该是叶节点上神经网络预测的动作还没有实施（叶节点拓展出来的子节点才是被实施后的情况），也就是说叶节点的状态不是 `board.current_player` 造成的，而是 `board.do_action()` 之前的 `current_player` 造成的，所以要对叶节点进行惩罚（加上了负号）。

项目是一年前写的，不确定描述的是否正确，https://www.cnblogs.com/zhiyiYo/p/14683450.html 是我做项目时写的博客，也许对你有点帮助。

**Comment by haormj** [comment]
@zhiyiYo 这个博客都看了好几遍了，哈哈哈，我自己在看看

**Comment by zhiyiYo** [comment]
> @zhiyiYo 这个博客都看了好几遍了，哈哈哈，我自己在看看

或许你可以按自己的想法先训练看看，如果效果不错的话，应该就没问题吧
