### ISSUE TITLE
Figure

### ISSUE THREAD

**Issue by yfang777** [zhiyiYo/Alpha-Gobang-Zero#6]
Hello，how do you draw these figures? I am writing a DQN paper these days and need to draw pictures like in your blog. Thx

**Comment by zhiyiYo** [comment]
你可以使用 utils/draw_game.py 来绘制棋谱，只要传入棋谱的 json 文件就行了

**Comment by yfang777** [comment]
我其实想问的是你blog里面卷积层的示例图是怎么画的？

**Comment by zhiyiYo** [comment]
这个是别人画的

**Comment by yfang777** [comment]
好的，谢谢
